include!("parts/foundation.rs");
include!("parts/verification.rs");
include!("parts/provenance.rs");
include!("parts/runtime.rs");
include!("parts/mining.rs");
include!("parts/miner_provenance.rs");
include!("parts/observability.rs");
include!("parts/entities.rs");
include!("parts/diagnostics.rs");
include!("parts/v2_4_compat.rs");
#[cfg(test)]
include!("parts/release_rehearsal.rs");
